kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sin"
processes = []

[build]
dockerfile = "./Dockerfile"

[[services]]
internal_port = 3000
processes = ["app"]
protocol = "tcp"
[services.concurrency]
hard_limit = 10000
soft_limit = 10000
type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
