name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only --wait-timeout 1800
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
